<?php
/**
 * Nette Framework Requirements Checker template.
 *
 * @param array    $requirements
 * @param bool     $errors
 * @param bool     $warnings
 */
header( 'modelContent-Type: text/html; charset=utf-8' );
header( 'Cache-Control: s-maxage=0, max-age=0, must-revalidate' );
header( 'Expires: Mon, 23 Jan 1978 10:00:00 GMT' );
?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="robots" content="noindex">
	<title><?php echo __( 'Система проверки совместимости веб сервера и Joostina CMS' ) ?></title>
	<style type="text/css">
		html {
			font: 13px/1.5 Verdana, sans-serif;
			border-top: 5.3em solid #F4EBDB;
		}

		body {
			border-top: 1px solid #E4DED5;
			margin: 0;
			background: white;
			color: #333;
		}

		#wrapper {
			max-width: 780px;
			margin: -5.3em auto 0;
		}

		h1 {
			font: 2.3em/1.5 sans-serif;
			margin: .5em 0 1.5em;
			/*background: url(assets/logo.png) right center no-repeat;*/
			color: #7A7772;
			text-shadow: 1px 1px 0 white;
		}

		h2 {
			font-size: 2em;
			font-weight: normal;
			color: #3484D2;
			margin: .7em 0;
		}

		p {
			margin: 1.2em 0;
		}

		.result {
			margin: 1.5em 0;
			padding: 0 1em;
			border: 2px solid white;
		}

		.passed h2 {
			color: #1A7E1E;
		}

		.failed h2 {
			color: white;
		}

		table {
			padding: 0;
			margin: 0;
			border-collapse: collapse;
			width: 100%;
		}

		table td, table th {
			text-align: left;
			padding: 10px;
			vertical-align: top;
			border-style: solid;
			border-width: 1px 0 0;
			border-color: inherit;
			background: white none no-repeat 12px 8px;
			background-color: inherit;
		}

		table th {
			font-size: 105%;
			font-weight: bold;
			padding-left: 50px;
		}

		.passed, .info {
			background-color: #E4F9E3;
			border-color: #C6E5C4;
		}

		.passed th {
			background-image: url('assets/passed.gif');
		}

		.info th {
			background-image: url('assets/info.gif');
		}

		.warning {
			background-color: #FEFAD4;
			border-color: #EEEE99;
		}

		.warning th {
			background-image: url('assets/warning.gif');
		}

		.failed {
			background-color: #F4D2D2;
			border-color: #D2B994;
		}

		div.failed {
			background-color: #CD1818;
			border-color: #CD1818;
		}

		.failed th {
			background-image: url('assets/failed.gif');
		}

		.description td {
			border-top: none !important;
			padding: 0 10px 10px 50px;
			color: #555;
		}

		.passed.description {
			display: none;
		}
	</style>

	<script src="assets/denied/checker.js" type="text/javascript"></script>
</head>

<body>
<div id="wrapper">
	<h1><?php echo __( 'Проверка конфигурации сервера и настроек PHP' ) ?></h1>

	<p><?php echo __( 'Скрипт проверяет версии и настройки веб сервера и параметры PHP требуемые для полноценной работы <a href="http://www.joostina.ru" target="_blank">Joostina CMS</a>' ) ?></p>

	<?php if ( $errors ): ?>
	<div class="failed result">
		<h2><?php echo __( 'Сожалеем, но Joostina CMS не сможет заработать на данном сервере' ) ?></h2>
	</div>
	<?php else: ?>
	<div class="passed result">
		<h2><?php echo __( 'Ура! Система подходит для <a href="install.php">установки</a> Joostina.' ) ?></h2>
		<?php if ( $warnings ): ?><p><strong><?php echo __( 'Система запустится, но не всё идеально, ознакомтесь со списком замечаний ниже.' ) ?></strong></p><?php endif ?>
	</div>
	<?php endif ?>


	<h2><?php echo __( 'Детали' ) ?></h2>

	<table>
		<?php foreach ( $requirements as $id => $requirement ): ?>
		<?php $class = isset( $requirement->passed ) ? ( $requirement->passed ? 'passed' : ( $requirement->required ? 'failed' : 'warning' ) ) : 'info' ?>
		<tr id="res<?php echo $id ?>" class="<?php echo $class ?>">
			<th><?php echo htmlSpecialChars( $requirement->title ) ?></th>

			<?php if ( empty( $requirement->passed ) && isset( $requirement->errorMessage ) ): ?>
			<td><?php echo htmlSpecialChars( $requirement->errorMessage ) ?></td>
			<?php elseif ( isset( $requirement->message ) ): ?>
			<td><?php echo htmlSpecialChars( $requirement->message ) ?></td>
			<?php elseif ( isset( $requirement->passed ) ): ?>
			<td><?php echo $requirement->passed ? __( 'Включено' ) : __( 'Выключено' ) ?></td>
			<?php else: ?>
			<td></td>
			<?php endif ?>
		</tr>

		<?php if ( isset( $requirement->description ) ): ?>
			<tr id="desc<?php echo $id ?>" class="<?php echo $class ?> description">
				<td colspan="2"><?php echo $requirement->description ?></td>
			</tr>
			<?php endif ?>

		<?php if ( isset( $requirement->script ) ): ?>
			<script type="text/javascript"><?php echo $requirement->script ?></script>
			<?php endif ?>

		<?php endforeach ?>
	</table>

	<?php if ( $errors ): ?><p>Please check the error messages and <a href="?">try again</a>.</p><?php endif ?>

	<p>
		<small> <?php echo sprintf( 'Скрипт проверки соответствий. Версия %s. Основан на оригинальной разработке %s' , CHECKER_VERSION , '<a href="http://www.nette.org/" target="_blank">Nette Framework</a>' ) ?></small>
	</p>
</div>
</body>
</html>